# Generated by Django 2.0.3 on 2018-03-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_horas_lectivas', '0002_auto_20180315_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseXTeacher',
            new_name='TeacherXCourse',
        ),
    ]
