# Generated by Django 2.0.3 on 2018-03-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_horas_lectivas', '0003_auto_20180315_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=300)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_horas_lectivas.Departament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usersystem',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_horas_lectivas.UserType'),
        ),
    ]
